<a href="https://colab.research.google.com/github/Bachechu/python/blob/main/24.05.03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#학생 수준 평가 시험에서 영어와 수학 점수가 합해서 100점 넘으면 합격(PASS)이다. 각 영어나 수학 점수가 40점 미만이면 과목 미달로 FAIL, 영어나 수학 점수를 입력받아 합계를 구한후 합불을 결정하라
# 첫번째 입력값이 영어, 두번째가 수학

a = list(map(int,input().split()))

if sum(a) > 100:
  if a[0] > 40 and a[1] > 40: #if 절 안에 if를 넣은 중첩 if를 and로 이어서 작성한 조건문
    print('PASS')
  elif a[0] < 40:
    print('ENG FAIL')
  else:
    print('MATH FAIL')
else:
  print('FAIL')

60 59
PASS


In [5]:
#N개의 숫자가 공백없이 입력된다 이 숫잗를 모두 합쳐서 합을 출력하는 프로그램을 작성하시오
#입력: 첫째 줄에 숫자 N가 주어짐

Num=input()
Num_list=list(Num)
aa=map(int,Num_list)

print(sum(aa))


5833743
33


In [9]:
#다음 리스트에서 확장자가 png나 jpg인 파일명, 확장자를 출력하는 파이썬 코드를 작성하시오
#첫째줄에 숫자 N이 주어진다. 결과가 리스트로 출럭

# sample1
#4
#alpha.hwp
#bravo.doc
#charlie.txt
#delta.png


n=int(input())
a=[input() for _ in range(n)]
b=[i for i in a if i.split('.')[-1]=='jpg' or i.split('.')[-1]=='png']
print(b)




















4
alpha.hwp
bravo.doc
charlie.txt
delta.png
['delta.png']


In [14]:
pip install numpy

In [16]:
import numpy as np


In [17]:
#넘파이 사용 이유: 큰 배열과 행렬 연산에 필요한 다양한 함수를 제공
#N차원배열(ndarray)을 효과적으로 다룰 수 있음
#넘파이(NumPy) 의 필요성 및 응용 분야
  # 효율적인 데이터 저장과 접근
  # 벡터화 연산
  # 다양한 수학 함수와 통계 연산 제공
  # 과학계산 및 데이터 분석



In [18]:
#함수()
#메소드()
#객체.메소드()
#객체.속성 -> 괄호가 안붙음
#ndarray 클래스 기본 속성
#ndarray.shape
#ndarray.size - 전체 원소 개수를 반환
#ndarray.ndim - 차원의 개수를 반환
#ndarray.dtype - 데이터 타입을 반환



In [21]:
arr=np.arange(1,10,2)
print(arr)


[1 3 5 7 9]


In [23]:
ones_2d=np.ones((3,4))
print(ones_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
arr=np.linspace(0,1,10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [66]:
#A행렬을 생성해보자.
# A의 모양(shape)을 출력해보자.
# 19 값을 추출해보자.
# 슬라이싱을 이용하여 [[1, 2], [6, 7]] 값을 추출해보자
# 슬라이싱을 이용하여 [[19, 20], [24, 25]] 값을 추출해보자.
# 슬라이싱을 이용하여 0축의 첫 번째 행과 두 번째 행을 추출해보자.
# 슬라이싱을 이용하여 1축의 마지막 열과 마지막 직전 열을 추출해보자.

A = np.array([[ 1, 2, 3, 4, 5],[ 6, 7, 8, 9, 10],[11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])
print(A.shape)
print(A[3,3])
print(A[0:2,0:2])
print(A[3:5,3:5])
print(A[0])
print(A[1])
print(A[:,-1])
print(A[:,-2])

(5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[1 2 3 4 5]
[ 6  7  8  9 10]
[ 5 10 15 20 25]
[ 4  9 14 19 24]


In [74]:
a = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]],[[25,26,27,28],[29,30,31,32],[33,34,35,36]]])
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)



(3, 3, 4)
36
3
int64


In [80]:
arr=np.arange(1,37)
print(arr)
arr_3d=arr.reshape(3,3,4)
print(arr_3d)
arr_343=arr.reshape(3,4,3)
print(arr_343)
arr_f=arr_343.flatten()
print(arr_f)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
